# -*- coding: utf-8 -*-
"""calculadora.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fVbb5kntElsgQelcoKdQWeBRm1ieFU7T
"""

inicio= input('Deseja iniciar os calculos? [s/n] ')
while inicio != "n":
  operacao= input('Digite a operação desejada. Soma, subitração, divisão ou multiplicação: ')
  numero1= input('Digite um numero: ')
  numero2= input('Digite outro numero: ')
  numero1= int(numero1)
  numero2= int(numero2)

  if operacao == "Soma":
    resultado=(numero1 + numero2)
  elif operacao == "multiplicação":
    resultado = (numero1 * numero2)
  elif operacao == "subitração":
    resultado=(numero1 - numero2)
  elif operacao == "divisão":
    resultado= (numero1 / numero2)
  else:
    "operação não reconhecida use,Soma, subitração, divisão ou multiplicação"
  print("O resultado da operação é de: ", str(resultado))
  inicio= input('Deseja iniciar os calculos? [s/n] ')